Test

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -29,7 +29,7 @@ jobs:
         - "9.8.2"
         #- "9.10.1"
         # FIXME: Add windows-latest back to CI once it is passing.
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        os: [windows-latest]
 
         # Action fails to install GHC < 8.10 on OSX with a generic error
         # messsage:
@@ -61,6 +61,34 @@ jobs:
       LD_LIBRARY_PATH: ${{ (matrix.os != 'windows-latest' && '/usr/local/lib') || '' }}
 
     steps:
+    - name: Test 1
+      run: |
+        echo "*** /"
+        ls /
+        echo "*** /msys64"
+        ls /msys64
+        echo "*** /bin"
+        ls /bin
+        echo "*** /usr/bin"
+        ls /usr/bin
+        echo "*** /mingw64"
+        ls /mingw64
+        echo "*** /mingw64/bin"
+        ls /mingw64/bin
+        echo "*** /mingw64/bin"
+        ls /mingw64/bin
+        #ls \
+        #echo LISTEN
+        #ls c:\
+        #echo YOU
+        #env:PATH = "C:\msys64\usr\bin;$env:PATH"
+        #which pacman || echo "pacman not found 1"
+        #which pacman.exe || echo "pacman not found 2"
+
+    - name: Test 2
+      run: |
+        C:\msys64\msys2_shell.cmd -mingw64 "which pacman || echo 'pacman not found 3'"
+
     - uses: haskell-actions/setup@v2
       with:
         ghc-version: ${{ matrix.ghc }}
